parserOptions:
  sourceType: 'module'
  ecmaVersion: 2015

env:
  es6: true
  browser: true
  commonjs: true

extends: 'htmlacademy/es6'

rules:
  camelcase: ["error", {allow: ["time_24hr", "base_price", "date_from", "date_to", "is_favorite"]}]
